name: task
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  persistent_bottom_nav_bar: ^4.0.2
  flutter_launcher_icons: ^0.10.0
  google_fonts: ^3.0.1
  provider: ^6.0.3
  shared_preferences: ^2.0.17
  fluttertoast: ^8.2.1
  url_launcher: ^6.1.10
#  flutter_stripe:
  flutter_stripe: ^9.2.0
  image_picker:


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_logo.jpg"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^1.1.5
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Orpheus Pro
      fonts:
        - asset: fonts/OrpheusPro-Bold.ttf
    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Bold.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Bold.ttf

